import { reportConfig } from "./config";
import { generatePeriodCalendar } from "./periods";
import type {
  BudgetMasterRow,
  MappingTableRow,
  RawActualDetailRow,
} from "./types";

export const periodCalendar = generatePeriodCalendar(
  reportConfig.report_year,
  reportConfig.default_period_count,
);

export const budgetMaster: BudgetMasterRow[] = [
  {
    id: "budget-sui-defi",
    year: 2026,
    token: "SUI",
    budget_program: "DeFi incentives",
    incentive_program: null,
    yearly_budget: 21_600_000,
    active_flag: true,
    budget_version: "v1-internal",
    approval_status: "confirmed",
    notes: "Confirmed example input from brief.",
  },
  {
    id: "budget-deep-main",
    year: 2026,
    token: "DEEP",
    budget_program: "DeFi incentives",
    incentive_program: "DEEP Main",
    yearly_budget: 200_000_000,
    active_flag: true,
    budget_version: "v1-internal",
    approval_status: "draft",
    notes: "Example reporting layer only. Final DEEP hierarchy remains configurable.",
  },
  {
    id: "budget-deep-moonshots",
    year: 2026,
    token: "DEEP",
    budget_program: "DeFi incentives",
    incentive_program: "Moonshots",
    yearly_budget: 91_670_000,
    active_flag: true,
    budget_version: "v1-internal",
    approval_status: "confirmed",
    notes: "Moonshots confirmed active DEEP program example.",
  },
  {
    id: "budget-ns-pending",
    year: 2026,
    token: "NS",
    budget_program: "Pending",
    incentive_program: null,
    yearly_budget: null,
    active_flag: true,
    budget_version: "v1-internal",
    approval_status: "pending",
    notes: "Final NS budget pending confirmation.",
  },
  {
    id: "budget-walrus-pending",
    year: 2026,
    token: "Walrus",
    budget_program: "Pending",
    incentive_program: null,
    yearly_budget: null,
    active_flag: true,
    budget_version: "v1-internal",
    approval_status: "pending",
    notes: "Final Walrus budget pending confirmation.",
  },
];

export const rawActualDetail: RawActualDetailRow[] = [
  {
    id: "actual-sui-1",
    token_raw: "SUI",
    program_raw: "defi_incentives",
    protocol_raw: "SuiLend",
    pool_raw: "Pool A",
    amount: 1_800_000,
    period_id: "P01",
    period_start: "2026-01-01",
    period_end: "2026-01-14",
    transaction_date: "2026-01-10",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-sui-2",
    token_raw: "SUI",
    program_raw: "defi_incentives",
    protocol_raw: "SuiLend",
    pool_raw: "Pool B",
    amount: 950_000,
    period_id: "P04",
    period_start: "2026-02-12",
    period_end: "2026-02-25",
    transaction_date: "2026-02-20",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-sui-3",
    token_raw: "SUI",
    program_raw: "defi_incentives",
    protocol_raw: "Bluefin",
    pool_raw: "Pool C",
    amount: 1_250_000,
    period_id: "P06",
    period_start: "2026-03-12",
    period_end: "2026-03-25",
    transaction_date: "2026-03-15",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-deep-main-1",
    token_raw: "DEEP",
    program_raw: "deep_main",
    protocol_raw: "DeepBook",
    pool_raw: "Main Market",
    amount: 12_000_000,
    period_id: "P02",
    period_start: "2026-01-15",
    period_end: "2026-01-28",
    transaction_date: "2026-01-21",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-deep-main-2",
    token_raw: "DEEP",
    program_raw: "deep_main",
    protocol_raw: "DeepBook",
    pool_raw: "Growth Pool",
    amount: 9_500_000,
    period_id: "P05",
    period_start: "2026-02-26",
    period_end: "2026-03-11",
    transaction_date: "2026-03-02",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-moonshots-1",
    token_raw: "DEEP",
    program_raw: "moonshots",
    protocol_raw: "Moonshots",
    pool_raw: "Season 1",
    amount: 7_200_000,
    period_id: "P03",
    period_start: "2026-01-29",
    period_end: "2026-02-11",
    transaction_date: "2026-02-05",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-moonshots-2",
    token_raw: "DEEP",
    program_raw: "moonshots",
    protocol_raw: "Moonshots",
    pool_raw: "Season 2",
    amount: 6_900_000,
    period_id: "P06",
    period_start: "2026-03-12",
    period_end: "2026-03-25",
    transaction_date: "2026-03-18",
    metadata: { source: "mock-obl" },
  },
  {
    id: "actual-unmapped-1",
    token_raw: "DEEP",
    program_raw: "legacy_unknown",
    protocol_raw: "Legacy Proto",
    pool_raw: "Archive Pool",
    amount: 1_150_000,
    period_id: "P04",
    period_start: "2026-02-12",
    period_end: "2026-02-25",
    transaction_date: "2026-02-18",
    metadata: { source: "mock-obl", issue: "pending mapping" },
  },
];

export const mappingTable: MappingTableRow[] = [
  {
    id: "map-sui-defi",
    token_raw: "SUI",
    program_raw: "defi_incentives",
    protocol_raw: null,
    pool_raw: null,
    mapped_token: "SUI",
    mapped_budget_program: "DeFi incentives",
    mapped_incentive_program: null,
    mapped_reporting_bucket: "SUI",
    active_flag: true,
    confidence: "high",
    notes: "Confirmed token-level mapping for skeleton.",
  },
  {
    id: "map-deep-main",
    token_raw: "DEEP",
    program_raw: "deep_main",
    protocol_raw: null,
    pool_raw: null,
    mapped_token: "DEEP",
    mapped_budget_program: "DeFi incentives",
    mapped_incentive_program: "DEEP Main",
    mapped_reporting_bucket: "DEEP Main",
    active_flag: true,
    confidence: "medium",
    notes: "Example mapping only. Final DEEP hierarchy remains configurable.",
  },
  {
    id: "map-moonshots",
    token_raw: "DEEP",
    program_raw: "moonshots",
    protocol_raw: null,
    pool_raw: null,
    mapped_token: "DEEP",
    mapped_budget_program: "DeFi incentives",
    mapped_incentive_program: "Moonshots",
    mapped_reporting_bucket: "Moonshots",
    active_flag: true,
    confidence: "high",
    notes: "Confirmed active DEEP program example.",
  },
];
